apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-management
  template:
    metadata:
      labels:
        app: library-management
    spec:
      containers:
      - name: library-management
        image: library-management:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: DB_URL
          value: "jdbc:mysql://db:3306/books"
        - name: SPRING_DATASOURCE_USERNAME
          value: "app_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"