apiVersion: v1
kind: Service
metadata:
  name: library-management-service
spec:
  selector:
    app: library-management
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer