name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-openjdk' # Добавьте эту строку
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t heisenberg7709/library-management .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push heisenberg7709/library-management

      - name: Deploy to Server
        run: |
          ssh user@yourserver "docker pull heisenberg7709/library-management && docker-compose -f docker-compose.yml up -d"
