name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: docker build -t heisenberg7709/library-management -f docker/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push heisenberg7709/library-management

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 heisenberg7709/library-management

      - name: Wait for application to be available
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/; then
              echo "Application is up!"
              exit 0
            else
              echo "Waiting for application to be up..."
              sleep 10
            fi
          done
          exit 1