name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'  # Триггер на все ветки
  pull_request:
    branches:
      - main  # Триггер на pull requests в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/library-management:latest -f docker/Dockerfile .

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/library-management:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/mysql-deployment.yaml
          kubectl apply -f kubernetes/mysql-service.yaml
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}